### ISSUE TITLE
Error on ArchLinux while using go get

### ISSUE THREAD

**Issue by blankoworld** [mrexodia/go-gitea-webhook#1]
While using the first command ```go get github.com/mrexodia/go-gitea-webhook```, I got this error:

```
od ~ % go get github.com/mrexodia/go-gitea-webhook
package code.gitea.io/sdk/gitea: unrecognized import path "code.gitea.io/sdk/gitea" (parse https://code.gitea.io/sdk/gitea?go-get=1: no go-import meta tags ())
```

I resolve this problem by using this repository (with ```git clone```) and with this command:

```bash
go get github.com/go-gitea/go-sdk 
```

Did I forget something?

**Comment by mrexodia** [comment]
I had the same problem, no idea why it’s happening since I’m not very
familiar with Go, sorry...

**Comment by blankoworld** [comment]
I think that we can change the line here: https://github.com/mrexodia/go-gitea-webhook/blob/master/go-gitea-webhook.go#L21

to something like that:

```go
	"github.com/user/stringutil"
```

as explained here: https://golang.org/doc/code.html#ImportPaths

So in our case, probably that: 

```go
	"github.com/go-gitea/go-sdk"
```

In worst case it doesn't work as now. In best case it works well :)

**Comment by mrexodia** [comment]
Pull requests are welcome. I would give you commit access, but it’s a bit
hard to do from my phone...

**Comment by blankoworld** [comment]
I'm patient ;)

I can create a tiny pull request, but as you, I'm not familiar with Go.
So try and see ^_^
